### ISSUE TITLE
Omit root selector from component group element checks

### ISSUE THREAD

**Issue by zeetea** [neetjn/py-component-controller#54]
I haven't figured out exactly *why* yet, but checking availability on elements in a component group with the root selector included in the iteration can cause subsequent elements to return false negatives. When the root selector isn't checked, the element is checked properly. Regardless, it makes more sense not to check for the root selector in a group of components, as this element should not actually be used on its own.

Instead of:
```python
for element in self.group.__group__:
    if not getattr(self.group, element).check.available():
        return False
return True
```
We should be using:
```python
for element in self.group.__group__:
    if element != '_':
        if not getattr(self.group, element).check.available():
            return False
return True
```

**Comment by neetjn** [comment]
https://github.com/neetjn/py-component-controller/pull/57
