### ISSUE TITLE
The wait_for function in the Elements class should return False if the conditions provided are not met and error is not specified.

### ISSUE THREAD

**Issue by zeetea** [neetjn/py-component-controller#59]
Currently, when trying to use `Elements.wait_for()` in a conditional context (e.g. `while Elements.wait_for(timeout=1, length=1)`) the condition will always be met because the Elements object is always returned. This will parse as True even if the selector for Elements has no matches. Given this use case, I think the `wait_for` function should return False if the condition is not met and an error is not thrown.

**Comment by neetjn** [comment]
https://github.com/neetjn/py-component-controller/pull/60
