### ISSUE TITLE
PYSCC - Wait_for evaluate error messages at run-time 

### ISSUE THREAD

**Issue by rorosentrater** [neetjn/py-component-controller#63]
For wait_for method errors, if there is any count check being performed return the # of items as evaluated at run-time in the error message.

**Comment by neetjn** [comment]
There's no plausible way to evaluate the errors at run time unless we pass a callable object that will evaluate the string for us. In which case, what I would rather do is update the default error messages to include the number of items found, current location, and current window title to help with debugging.

**Comment by neetjn** [comment]
https://github.com/neetjn/py-component-controller/pull/67
