### ISSUE TITLE
Component_elements.text() can return StaleElementReferenceExceptions

### ISSUE THREAD

**Issue by zeetea** [neetjn/py-component-controller#92]
1. Describe your issue:
At times, when using `component_elements.text()`, a `StaleElementReferenceException` is thrown. This is due to the function leveraging `component_elements.get()`, returning a list of `WebElement` objects that can become stale by the time the function tries to pull the text from them. This occurs more often with large groups of elements.

2. Can you reproduce the issue?

3. On which python and selenium version does the issue appear?
This has been observed to occur on Python 2.7 using Selenium version 3.6.0.

4. Which version of py-component-controller does it affect?
All versions through 0.2.0.

5. How would you tag this issue?

  - [ ] Question
  - [x] Bug
  - [ ] Discussion
  - [ ] Feature request
  - [ ] Tip
  - [ ] Enhancement
  - [ ] Performance

**Comment by neetjn** [comment]
https://github.com/neetjn/py-component-controller/pull/93

**Comment by zeetea** [comment]
Issue persists in py-component-controller 0.2.1. In the function `__wait_elements_not_stale()`, `element.text` should be `element.text()`.
