### ISSUE TITLE
Documentation makes it unclear whether Service class is supposed to inherit from Controller.

### ISSUE THREAD

**Issue by zeetea** [neetjn/py-component-controller#95]
1. Describe your issue:
In the docs for the `Service` class, the example uses `self.navigate()`, a controller function. However, `Service` does not inherit from `Controller`, and therefore does not have access to `self.navigate()`. It's not clear whether the mistake is in the docs or in the codebase.

As a side note, the implementation example in the same doc has a couple of mistakes: `Product` is used in the call to `super` instead of `Google`, and `self` is missing from the function definition for `number_of_results`.

2. Can you reproduce the issue?
Yes; the code example in the documentation for `Service` reproduces it.

3. On which python and selenium version does the issue appear?
Observed to occur on Python 2.7 and Selenium 3.6.0.

4. Which version of py-component-controller does it affect?
0.2.0 and 0.2.1.

5. How would you tag this issue?

  - [x] Question
  - [x] Bug
  - [ ] Discussion
  - [ ] Feature request
  - [ ] Tip
  - [ ] Enhancement
  - [ ] Performance

**Comment by neetjn** [comment]
I'll bind the controller instance to generated services in 0.2.2, as well as clean up the docs. 0.2.x so far has been a rush job.

**Comment by neetjn** [comment]
Binded controller reference to services, removed controller references for components in 0.2.2.
